spring:
  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url:jdbc:mysql://cdb-e7gws0jm.bj.tencentcdb.com:10150/blog?useUnicode=true&characterEncoding=utf-8
    password: ""

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.tck: info
  file: log/blog-pro.log
server:
  port: 8082
